import { useState } from 'react';
import { View, Text, Pressable, StyleSheet } from 'react-native';
import { router } from 'expo-router';
import { ChevronLeft, ChevronRight, Check } from 'lucide-react-native';
import { activitiesApi } from '../api/activities';

export default function Activity() {
  const [step, setStep] = useState(0);
  const [answer, setAnswer] = useState('');
  const [error, setError] = useState('');
  const options = ['🪔 Diya', '🍎 Apple', '📱 Phone'];
  if (step === 2) return <View style={s.center}><Text style={s.big}>🌟</Text><Text style={s.eyebrow}>ACTIVITY COMPLETE</Text><Text style={s.heading}>Great work!</Text><Text style={s.sub}>You completed today&apos;s activity.</Text>{error ? <Text style={s.error}>{error}</Text> : null}<View style={s.result}><Text style={s.resultNum}>80%</Text><Text style={s.sub}>Your activity score</Text><Text style={s.streak}>✦ +20 XP · 🔥 5 day streak</Text></View><Pressable style={s.primary} onPress={async () => { try { await activitiesApi.attempt('memory-match', 80); router.replace('/(tabs)'); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Could not save progress'); } }}><Text style={s.primaryText}>Return home</Text></Pressable></View>;
  return <View style={s.screen}><Pressable onPress={() => router.back()} style={s.back}><ChevronLeft color="#2E6458"/><Text>Back</Text></Pressable><Text style={s.eyebrow}>MEMORY · EASY</Text><Text style={s.heading}>{step === 0 ? 'Remember these objects' : 'Which object did you see?'}</Text>{step === 0 ? <><Text style={s.sub}>Look carefully. Take your time.</Text><View style={s.objects}><Text style={s.object}>🪔</Text><Text style={s.object}>🍎</Text><Text style={s.object}>🌸</Text><Text style={s.object}>🧺</Text></View><Pressable style={s.primary} onPress={() => setStep(1)}><Text style={s.primaryText}>I&apos;m ready</Text><ChevronRight color="#fff"/></Pressable></> : <><Text style={s.sub}>Choose one familiar object.</Text><View style={s.options}>{options.map(option => <Pressable key={option} onPress={() => setAnswer(option)} style={[s.option, answer === option && s.chosen]}><Text>{option}</Text></Pressable>)}</View><Pressable disabled={!answer} style={[s.primary, !answer && s.disabled]} onPress={() => setStep(2)}><Text style={s.primaryText}>Check answer</Text><Check color="#fff"/></Pressable></>}</View>;
}

const s = StyleSheet.create({ screen:{flex:1,backgroundColor:'#F8F8F5',padding:24,paddingTop:60}, center:{flex:1,backgroundColor:'#F8F8F5',padding:28,alignItems:'center',justifyContent:'center'}, back:{flexDirection:'row',alignItems:'center',gap:4,marginBottom:45}, eyebrow:{fontSize:10,letterSpacing:1.5,color:'#9CA9A4',fontWeight:'700',marginBottom:12}, heading:{fontSize:31,fontWeight:'700',color:'#243432',marginBottom:9}, sub:{fontSize:15,color:'#71807D',lineHeight:23}, error:{color:'#A94C43',marginTop:18,textAlign:'center'}, objects:{backgroundColor:'#EFF5F0',borderRadius:20,padding:30,flexDirection:'row',justifyContent:'space-around',marginVertical:38}, object:{fontSize:48}, primary:{backgroundColor:'#2E6458',borderRadius:12,padding:17,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8}, primaryText:{color:'#fff',fontSize:15,fontWeight:'700'}, options:{gap:10,marginVertical:30}, option:{backgroundColor:'#fff',borderWidth:1,borderColor:'#E5E9E2',padding:18,borderRadius:13}, chosen:{borderColor:'#71A487',backgroundColor:'#E4F1E9'}, disabled:{opacity:.45}, big:{fontSize:50,marginBottom:18}, result:{backgroundColor:'#fff',borderRadius:18,padding:24,width:'100%',alignItems:'center',marginVertical:30}, resultNum:{fontSize:42,fontWeight:'700',color:'#2E6458'}, streak:{color:'#B57847',fontWeight:'700',marginTop:14} });
