import { useEffect, useState } from 'react';
import { View, Text, Pressable, StyleSheet, ScrollView } from 'react-native';
import { ChevronRight, Phone, Volume2, WifiOff } from 'lucide-react-native';
import { router } from 'expo-router';
import { patientsApi } from '../../api/patients';
import { activitiesApi } from '../../api/activities';
import { VoiceService } from '../../services/voice';

const t = { goodMorning: 'Good morning', progress: "Today's progress", startActivity: "Start today's activity", mood: 'How are you feeling?' };

export default function Home() {
  const [progress, setProgress] = useState(0);
  const [activityTitles, setActivityTitles] = useState<string[]>([]);
  useEffect(() => { patientsApi.dashboard().then(data => setProgress(data.today.progress)).catch(() => setProgress(0)); activitiesApi.today().then(items => setActivityTitles(items.map(item => item.title))).catch(() => setActivityTitles([])); }, []);
  return <ScrollView contentContainerStyle={s.wrap}>
    <View style={s.header}><View><Text style={s.eyebrow}>TUESDAY, AUGUST 27, 2026</Text><Text style={s.title}>{t.goodMorning}, Asha 👋</Text><Text style={s.sub}>A gentle start to a meaningful day.</Text></View><Pressable accessibilityLabel="Listen to today&apos;s activities" onPress={() => VoiceService.speak(`Good morning Asha. Today's activities are ${activityTitles.length ? activityTitles.join(', ') : 'loading'}. You have completed ${progress} percent of your activities.`)} style={s.listen}><Volume2 size={19} color="#2E6458"/><Text>Listen</Text></Pressable></View>
    <View style={s.hero}><Text style={s.eyebrow}>YOUR DAILY RHYTHM</Text><Text style={s.heroTitle}>A little progress{`\n`}<Text style={{ color:'#4F8471' }}>goes a long way.</Text></Text><Text style={s.heroSub}>Take a few minutes for yourself today.</Text><Pressable style={s.primary} onPress={() => router.push('/activity')}><Text style={s.primaryText}>{t.startActivity}</Text><ChevronRight color="#fff" size={20}/></Pressable></View>
    <View style={s.card}><View style={s.row}><Text style={s.label}>{t.progress}</Text><Text style={s.percent}>{progress}%</Text></View><View style={s.track}><View style={[s.fill, { width:`${progress}%` }]} /></View><View style={s.row}><Text style={s.muted}>Progress from shared account</Text><Text style={s.streak}>✦ 5 day streak</Text></View></View>
    <View style={s.quick}><Quick icon="😊" text={t.mood} color="#F8EFD1" onPress={() => router.push('/mood')}/><Quick icon="🖼️" text="My memories" color="#EDEAF5" onPress={() => router.push('/memories')}/><Quick icon="🔔" text="My reminders" color="#E4F1EA" onPress={() => router.push('/reminders')}/></View>
    <Pressable style={s.caregiver} onPress={() => router.push('/caregiver')}><View style={s.phone}><Phone size={21} color="#2E6458"/></View><View style={{ flex:1 }}><Text style={s.careTitle}>Need to talk to someone?</Text><Text style={s.muted}>Meera is just a call away.</Text></View><ChevronRight color="#8CA098"/></Pressable>
    <View style={s.offline}><WifiOff size={15} color="#B17D55"/><Text style={s.offlineText}>Connected to shared care data.</Text></View>
  </ScrollView>;
}

function Quick({ icon, text, color, onPress }: { icon:string; text:string; color:string; onPress:()=>void }) { return <Pressable onPress={onPress} style={[s.quickCard, { backgroundColor:color }]}><Text style={s.quickIcon}>{icon}</Text><Text style={s.quickText}>{text}</Text><ChevronRight size={16} color="#81938B"/></Pressable>; }
const s = StyleSheet.create({ wrap:{padding:22,paddingBottom:110,backgroundColor:'#F8F8F5',gap:15}, header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',marginBottom:7}, eyebrow:{fontSize:10,letterSpacing:1.4,color:'#9CA9A4',fontWeight:'700',marginBottom:9}, title:{fontSize:30,fontWeight:'600',color:'#243432'}, sub:{fontSize:14,color:'#71807D',marginTop:6}, listen:{flexDirection:'row',alignItems:'center',gap:6,padding:10,backgroundColor:'#E8F0EA',borderRadius:10}, hero:{backgroundColor:'#DFEEE5',borderRadius:20,padding:24,minHeight:225}, heroTitle:{fontSize:29,fontWeight:'700',color:'#243432',lineHeight:35,marginTop:12}, heroSub:{fontSize:13,color:'#648075',marginTop:10,marginBottom:20}, primary:{backgroundColor:'#2E6458',borderRadius:11,padding:15,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:6}, primaryText:{color:'#fff',fontSize:14,fontWeight:'700'}, card:{backgroundColor:'#fff',borderRadius:18,padding:21,borderWidth:1,borderColor:'#E5E9E2'}, row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}, label:{fontSize:14,color:'#5A6965'}, percent:{fontSize:26,fontWeight:'700',color:'#2E6458'}, track:{height:9,backgroundColor:'#EDF0EB',borderRadius:9,marginVertical:18,overflow:'hidden'}, fill:{height:9,backgroundColor:'#75A990',borderRadius:9}, muted:{fontSize:11,color:'#98A39E'}, streak:{fontSize:12,color:'#B57847',fontWeight:'700'}, quick:{gap:10}, quickCard:{minHeight:72,borderRadius:15,padding:15,flexDirection:'row',alignItems:'center',gap:13}, quickIcon:{fontSize:26}, quickText:{fontSize:15,fontWeight:'600',flex:1}, caregiver:{backgroundColor:'#fff',borderRadius:15,padding:14,flexDirection:'row',alignItems:'center',gap:11,borderWidth:1,borderColor:'#E5E9E2'}, phone:{backgroundColor:'#E9F1EC',borderRadius:11,padding:10}, careTitle:{fontSize:13,fontWeight:'700',marginBottom:3}, offline:{flexDirection:'row',alignItems:'center',gap:7,justifyContent:'center'}, offlineText:{fontSize:10,color:'#9B8A7A'} });
